### ISSUE TITLE
시험관련 질문

### ISSUE THREAD

**Issue by minsuuuj** [tjwldnjss13/Programming-principles-and-practice_001_2101#9]
안녕하십니까 조교님, 시험 관련하여 질문드립니다. 프로그래밍 실기 시험이 있나요? 필기만 준비하면 되는건가요? 실기문제가 있다면 과제문제를 처음부터 다시 연습해보려 합니다.
또 시험환경은 visual studio로 진행될 것이라고 생각되는데 CRT_SECURE_NO_WARNING 오류에 관해서는 생각하지 않아도 되나요? 아니면 이 오류까지 처리를 해야하나요. 만약 제출을 소스코드만 제출을 한다면 소스코드 내에서 오류처리를 해야하는지 궁금합니다. 현재 저는 프로젝트 설정 상에서 처리를 하여 공부 중이라 소스코드 내에서 처리하는 방법을 공부해야 하는지 고민되어 질문드립니다.

**Comment by tjwldnjss13** [comment]
시험은 필기형식으로만 진행됩니다.
